"""initial schema

Revision ID: 6761164d8997
Revises: 
Create Date: 2026-05-31 14:05:00.435616

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import inspect

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6761164d8997'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    if inspect(op.get_bind()).has_table("orders"):
        return
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('net_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('abholzeit', sa.String(), nullable=True),
    sa.Column('togo', sa.String(), nullable=True),
    sa.Column('num_items_sold', sa.Integer(), nullable=True),
    sa.Column('returning_customer', sa.Boolean(), nullable=True),
    sa.Column('date_paid', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('picked_up', sa.Boolean(), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handed_out', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('handed_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
